# Generated by Django 3.1.4 on 2020-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FastFoodChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_food', models.CharField(blank=None, choices=[("McDonald's", "McDonald's"), ('KFC', 'KFC'), ('Subway', 'Subway'), ('Burger King', 'Burger King')], default="McDonald's", max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='McDonnaldsFastFoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_McFood', models.CharField(blank=None, choices=[('McBurger', 'McBurger'), ('McToast', 'McToast'), ('McFlurry', 'McFlurry')], default='McBurger', max_length=25)),
            ],
        ),
    ]
