# Generated by Django 3.1.4 on 2020-12-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyOrder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='McDonnaldsFastFoods',
            new_name='McDonaldsFastFoods',
        ),
    ]
