# Generated by Django 3.1.4 on 2020-12-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyOrder', '0002_auto_20201211_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcdonaldsfastfoods',
            name='name_of_McFood',
            field=models.CharField(blank=None, choices=[('McBurger', 'McBurger'), ('McToast', 'McToast'), ('McFlurry', 'McFlurry')], default='McBurger', max_length=25),
        ),
    ]
